### PR TITLE
Added data model

### PR DESCRIPTION
**Pull request by vladkinoman**
Update ClassDiagram and added a data model to the project which was got from @Jeanosis branch.

### CODE REVIEW

**Comment by harrytallbelt** [comment]
It seems there is a typo in Actor and Director classes. They ment to be derived from Person, but they are derived from BaseEntity instead.

**Comment by harrytallbelt** [comment]
Also, shouldn't BaseEntity and Person be abstract? Or is it some kind of EF limitation? Just asking, I'm aware it isn't that much of a problem. :)

**Comment by harrytallbelt** [comment]
Same kind of typo in Client class.

**Comment by vladkinoman** [comment]
I'm so sorry for my mistakes. I was sleepy last night. :(
I'll fix it in the next update)

**Pull request merged**
